# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Distribution_analisys(object):
    def setupUi(self, Distribution_analisys):
        Distribution_analisys.setObjectName("Distribution_analisys")
        Distribution_analisys.resize(1105, 869)
        self.centralwidget = QtWidgets.QWidget(Distribution_analisys)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1081, 796))
        self.tabWidget.setObjectName("tabWidget")
        self.Image = QtWidgets.QWidget()
        self.Image.setObjectName("Image")
        self.Source_label = QtWidgets.QLabel(self.Image)
        self.Source_label.setGeometry(QtCore.QRect(9, 9, 67, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Source_label.setFont(font)
        self.Source_label.setObjectName("Source_label")
        self.Source_comboBox = QtWidgets.QComboBox(self.Image)
        self.Source_comboBox.setGeometry(QtCore.QRect(9, 39, 161, 31))
        self.Source_comboBox.setObjectName("Source_comboBox")
        self.Source_comboBox.addItem("")
        self.Source_comboBox.addItem("")
        self.Log_textBrowser = QtWidgets.QTextBrowser(self.Image)
        self.Log_textBrowser.setGeometry(QtCore.QRect(7, 600, 256, 151))
        self.Log_textBrowser.setObjectName("Log_textBrowser")
        self.Left_pic = QtWidgets.QWidget(self.Image)
        self.Left_pic.setGeometry(QtCore.QRect(10, 210, 462, 261))
        self.Left_pic.setObjectName("Left_pic")
        self.Log_label = QtWidgets.QLabel(self.Image)
        self.Log_label.setGeometry(QtCore.QRect(7, 570, 39, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Log_label.setFont(font)
        self.Log_label.setObjectName("Log_label")
        self.Source_file_lineEdit = QtWidgets.QLineEdit(self.Image)
        self.Source_file_lineEdit.setGeometry(QtCore.QRect(206, 39, 431, 31))
        self.Source_file_lineEdit.setText("")
        self.Source_file_lineEdit.setObjectName("Source_file_lineEdit")
        self.Quality_textBrowser = QtWidgets.QTextBrowser(self.Image)
        self.Quality_textBrowser.setGeometry(QtCore.QRect(300, 600, 256, 151))
        self.Quality_textBrowser.setObjectName("Quality_textBrowser")
        self.Quality_label = QtWidgets.QLabel(self.Image)
        self.Quality_label.setGeometry(QtCore.QRect(297, 570, 234, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Quality_label.setFont(font)
        self.Quality_label.setObjectName("Quality_label")
        self.Left_pic_label = QtWidgets.QLabel(self.Image)
        self.Left_pic_label.setGeometry(QtCore.QRect(10, 165, 211, 31))
        self.Left_pic_label.setText("")
        self.Left_pic_label.setObjectName("Left_pic_label")
        self.Right_pic_label = QtWidgets.QLabel(self.Image)
        self.Right_pic_label.setGeometry(QtCore.QRect(540, 175, 191, 31))
        self.Right_pic_label.setText("")
        self.Right_pic_label.setObjectName("Right_pic_label")
        self.Settings_label = QtWidgets.QLabel(self.Image)
        self.Settings_label.setGeometry(QtCore.QRect(10, 523, 135, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Settings_label.setFont(font)
        self.Settings_label.setObjectName("Settings_label")
        self.Camera_spinBox = QtWidgets.QSpinBox(self.Image)
        self.Camera_spinBox.setGeometry(QtCore.QRect(670, 40, 91, 31))
        self.Camera_spinBox.setObjectName("Camera_spinBox")
        self.File_label = QtWidgets.QLabel(self.Image)
        self.File_label.setGeometry(QtCore.QRect(210, 10, 38, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.File_label.setFont(font)
        self.File_label.setObjectName("File_label")
        self.Camera_label = QtWidgets.QLabel(self.Image)
        self.Camera_label.setGeometry(QtCore.QRect(670, 10, 76, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Camera_label.setFont(font)
        self.Camera_label.setObjectName("Camera_label")
        self.start_button = QtWidgets.QPushButton(self.Image)
        self.start_button.setGeometry(QtCore.QRect(580, 700, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.Right_pic = QtWidgets.QWidget(self.Image)
        self.Right_pic.setGeometry(QtCore.QRect(540, 210, 461, 261))
        self.Right_pic.setObjectName("Right_pic")
        self.Write_file_lineEdit = QtWidgets.QLineEdit(self.Image)
        self.Write_file_lineEdit.setGeometry(QtCore.QRect(580, 630, 431, 31))
        self.Write_file_lineEdit.setText("")
        self.Write_file_lineEdit.setObjectName("Write_file_lineEdit")
        self.Write_file_label = QtWidgets.QLabel(self.Image)
        self.Write_file_label.setGeometry(QtCore.QRect(584, 601, 131, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Write_file_label.setFont(font)
        self.Write_file_label.setObjectName("Write_file_label")
        self.splitter = QtWidgets.QSplitter(self.Image)
        self.splitter.setGeometry(QtCore.QRect(150, 530, 511, 20))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.Nmb_box = QtWidgets.QCheckBox(self.splitter)
        self.Nmb_box.setObjectName("Nmb_box")
        self.Total_area_box = QtWidgets.QCheckBox(self.splitter)
        self.Total_area_box.setObjectName("Total_area_box")
        self.Avr_box = QtWidgets.QCheckBox(self.splitter)
        self.Avr_box.setObjectName("Avr_box")
        self.Lrst_box = QtWidgets.QCheckBox(self.splitter)
        self.Lrst_box.setObjectName("Lrst_box")
        self.tabWidget.addTab(self.Image, "")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.gridLayout = QtWidgets.QGridLayout(self.Settings)
        self.gridLayout.setObjectName("gridLayout")
        self.Source_label_2 = QtWidgets.QLabel(self.Settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Source_label_2.setFont(font)
        self.Source_label_2.setObjectName("Source_label_2")
        self.gridLayout.addWidget(self.Source_label_2, 0, 0, 1, 1)
        self.Source_label_4 = QtWidgets.QLabel(self.Settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Source_label_4.setFont(font)
        self.Source_label_4.setObjectName("Source_label_4")
        self.gridLayout.addWidget(self.Source_label_4, 0, 3, 1, 1)
        self.Resol_1th_lineEdit = QtWidgets.QLineEdit(self.Settings)
        self.Resol_1th_lineEdit.setObjectName("Resol_1th_lineEdit")
        self.gridLayout.addWidget(self.Resol_1th_lineEdit, 1, 0, 1, 1)
        self.Source_label_3 = QtWidgets.QLabel(self.Settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Source_label_3.setFont(font)
        self.Source_label_3.setObjectName("Source_label_3")
        self.gridLayout.addWidget(self.Source_label_3, 1, 1, 1, 1)
        self.Resol_2th_lineEdit = QtWidgets.QLineEdit(self.Settings)
        self.Resol_2th_lineEdit.setObjectName("Resol_2th_lineEdit")
        self.gridLayout.addWidget(self.Resol_2th_lineEdit, 1, 2, 1, 1)
        self.Blur_spinBox = QtWidgets.QSpinBox(self.Settings)
        self.Blur_spinBox.setObjectName("Blur_spinBox")
        self.gridLayout.addWidget(self.Blur_spinBox, 1, 3, 1, 1)
        self.Source_label_5 = QtWidgets.QLabel(self.Settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Source_label_5.setFont(font)
        self.Source_label_5.setObjectName("Source_label_5")
        self.gridLayout.addWidget(self.Source_label_5, 2, 0, 1, 3)
        self.Source_label_6 = QtWidgets.QLabel(self.Settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Source_label_6.setFont(font)
        self.Source_label_6.setObjectName("Source_label_6")
        self.gridLayout.addWidget(self.Source_label_6, 2, 3, 1, 1)
        self.Thr_lower_lineEdit = QtWidgets.QLineEdit(self.Settings)
        self.Thr_lower_lineEdit.setObjectName("Thr_lower_lineEdit")
        self.gridLayout.addWidget(self.Thr_lower_lineEdit, 3, 0, 1, 3)
        self.Threshold_upper_lineEdit = QtWidgets.QLineEdit(self.Settings)
        self.Threshold_upper_lineEdit.setObjectName("Threshold_upper_lineEdit")
        self.gridLayout.addWidget(self.Threshold_upper_lineEdit, 3, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(388, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 4, 1, 1)
        self.Source_label_13 = QtWidgets.QLabel(self.Settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Source_label_13.setFont(font)
        self.Source_label_13.setObjectName("Source_label_13")
        self.gridLayout.addWidget(self.Source_label_13, 4, 0, 1, 3)
        self.Source_label_14 = QtWidgets.QLabel(self.Settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Source_label_14.setFont(font)
        self.Source_label_14.setObjectName("Source_label_14")
        self.gridLayout.addWidget(self.Source_label_14, 4, 3, 1, 1)
        self.Gauss_thr_1th_spinBox = QtWidgets.QSpinBox(self.Settings)
        self.Gauss_thr_1th_spinBox.setEnabled(True)
        self.Gauss_thr_1th_spinBox.setObjectName("Gauss_thr_1th_spinBox")
        self.gridLayout.addWidget(self.Gauss_thr_1th_spinBox, 5, 0, 1, 1)
        self.Gauss_thr_2th_spinBox = QtWidgets.QSpinBox(self.Settings)
        self.Gauss_thr_2th_spinBox.setObjectName("Gauss_thr_2th_spinBox")
        self.gridLayout.addWidget(self.Gauss_thr_2th_spinBox, 5, 2, 1, 1)
        self.Min_area = QtWidgets.QLineEdit(self.Settings)
        self.Min_area.setObjectName("Min_area")
        self.gridLayout.addWidget(self.Min_area, 5, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 569, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.tabWidget.addTab(self.Settings, "")
        Distribution_analisys.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Distribution_analisys)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1105, 26))
        self.menubar.setObjectName("menubar")
        Distribution_analisys.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Distribution_analisys)
        self.statusbar.setObjectName("statusbar")
        Distribution_analisys.setStatusBar(self.statusbar)

        self.retranslateUi(Distribution_analisys)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Distribution_analisys)

    def retranslateUi(self, Distribution_analisys):
        _translate = QtCore.QCoreApplication.translate
        Distribution_analisys.setWindowTitle(_translate("Distribution_analisys", "MainWindow"))
        self.Source_label.setText(_translate("Distribution_analisys", "Source:"))
        self.Source_comboBox.setItemText(0, _translate("Distribution_analisys", "File"))
        self.Source_comboBox.setItemText(1, _translate("Distribution_analisys", "Camera"))
        self.Log_textBrowser.setHtml(_translate("Distribution_analisys", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Log_label.setText(_translate("Distribution_analisys", "Log:"))
        self.Quality_textBrowser.setHtml(_translate("Distribution_analisys", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Quality_label.setText(_translate("Distribution_analisys", "Quality of the distribution:"))
        self.Settings_label.setText(_translate("Distribution_analisys", "Settings of log:"))
        self.File_label.setText(_translate("Distribution_analisys", "File:"))
        self.Camera_label.setText(_translate("Distribution_analisys", "Camera:"))
        self.start_button.setText(_translate("Distribution_analisys", "Start Analisys"))
        self.Write_file_label.setText(_translate("Distribution_analisys", "Write to file:"))
        self.Nmb_box.setText(_translate("Distribution_analisys", "Number of contours"))
        self.Total_area_box.setText(_translate("Distribution_analisys", "Total area"))
        self.Avr_box.setText(_translate("Distribution_analisys", "Average area"))
        self.Lrst_box.setText(_translate("Distribution_analisys", "Largest areas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Image), _translate("Distribution_analisys", "Image"))
        self.Source_label_2.setText(_translate("Distribution_analisys", "Resolution:"))
        self.Source_label_4.setText(_translate("Distribution_analisys", "Gauss Blur:"))
        self.Resol_1th_lineEdit.setText(_translate("Distribution_analisys", "1280"))
        self.Source_label_3.setText(_translate("Distribution_analisys", "X"))
        self.Resol_2th_lineEdit.setText(_translate("Distribution_analisys", "720"))
        self.Source_label_5.setText(_translate("Distribution_analisys", "Threshold lower limit:"))
        self.Source_label_6.setText(_translate("Distribution_analisys", "Threshold Upper limit:"))
        self.Thr_lower_lineEdit.setText(_translate("Distribution_analisys", "160"))
        self.Threshold_upper_lineEdit.setText(_translate("Distribution_analisys", "255"))
        self.Source_label_13.setText(_translate("Distribution_analisys", "Gaussian adaptive threshhold:"))
        self.Source_label_14.setText(_translate("Distribution_analisys", "Minimum contour area:"))
        self.Min_area.setText(_translate("Distribution_analisys", "10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Settings), _translate("Distribution_analisys", "Settings"))


